import { getAvailableCheckoutDartCounts, isValidCheckoutAttempt } from '../../campaignModes/rivalEngine.js'
export const GAME_201_DEFAULTS = Object.freeze({ dartLimit: 12, successGoal: 5 })
export function create201State(config = {}) { return { startValue:201, remaining:201, dartsThisRound:0, successes:0, totalDarts:0, totalPointsScored:0, highestScore:0, highestFinish:0, successfulRounds:0, failedRounds:0, highestReachedStartValue:201, complete:false, visits:[], rounds:[], config:{...GAME_201_DEFAULTS,...config} } }
export function record201Visit(state, { score=0, darts=3, checkout=false } = {}) {
  if (state.complete) return state
  const remainingDarts=state.config.dartLimit-state.dartsThisRound
  const requestedDarts=checkout?Number(darts)||3:3
  const used=Math.max(1,Math.min(3,requestedDarts,remainingDarts)); const visitScore=Math.max(0,Math.min(180,Number(score)||0)); const checkoutValid=checkout&&visitScore===state.remaining&&isValidCheckoutAttempt(visitScore,used); const nextRemaining=state.remaining-visitScore; const bust=nextRemaining<0||nextRemaining===1||(nextRemaining===0&&!checkoutValid); const scored=bust?0:visitScore; const remaining=bust?state.remaining:nextRemaining; const totalDarts=state.totalDarts+used; const dartsThisRound=state.dartsThisRound+used; const success=checkoutValid&&!bust&&remaining===0; const failed=!success&&dartsThisRound>=state.config.dartLimit; const roundDone=success||failed; const successes=state.successes+Number(success); const nextStart=success?state.startValue+10:failed?Math.max(201,state.startValue-10):state.startValue; const round=roundDone?{startValue:state.startValue,success,dartsUsed:dartsThisRound,finish:success?visitScore:0,completedAt:new Date().toISOString()}:null
  const visit={startValue:state.startValue,score:scored,enteredScore:visitScore,rest:roundDone?0:remaining,darts:used,bust,checkout:success,createdAt:new Date().toISOString()}
  return {...state,startValue:nextStart,remaining:roundDone?nextStart:remaining,dartsThisRound:roundDone?0:dartsThisRound,successes,totalDarts,totalPointsScored:state.totalPointsScored+scored,highestScore:Math.max(state.highestScore,scored),highestFinish:Math.max(state.highestFinish,success?visitScore:0),successfulRounds:state.successfulRounds+Number(success),failedRounds:state.failedRounds+Number(failed),highestReachedStartValue:Math.max(state.highestReachedStartValue,nextStart),complete:successes>=state.config.successGoal,visits:[...state.visits,visit],rounds:round?[...state.rounds,round]:state.rounds}
}
export const get201Average = (state) => state.totalDarts ? state.totalPointsScored/state.totalDarts*3 : 0
export const get201CheckoutDartCounts = (state) => getAvailableCheckoutDartCounts(state.remaining).filter((darts) => darts <= state.config.dartLimit-state.dartsThisRound)
