export const levels = [
  {
    id: 1,
    title: "Level 1",
    type: "single",
    difficulty: "Anfänger",
    task: "Triff 3x Single 20",
    minArrows: 3,
    maxArrows: 9,
    rewardXP: 20,
    rewardCoins: 10,
    boss: false,
  },

  {
    id: 2,
    title: "Level 2",
    type: "single",
    difficulty: "Anfänger",
    task: "Triff 3x Single 19",
    minArrows: 3,
    maxArrows: 9,
    rewardXP: 25,
    rewardCoins: 15,
    boss: false,
  },

  {
    id: 3,
    title: "Level 3",
    type: "single",
    difficulty: "Anfänger",
    task: "Triff 3x Single 18",
    minArrows: 3,
    maxArrows: 9,
    rewardXP: 30,
    rewardCoins: 20,
    boss: false,
  },

  {
    id: 4,
    title: "Level 4",
    type: "single",
    difficulty: "Anfänger",
    task: "Triff 5x Single 20",
    minArrows: 5,
    maxArrows: 9,
    rewardXP: 35,
    rewardCoins: 20,
    boss: false,
  },

  {
    id: 5,
    title: "Level 5",
    type: "double",
    difficulty: "Anfänger",
    task: "Triff 2x Doppel 20",
    minArrows: 2,
    maxArrows: 9,
    rewardXP: 40,
    rewardCoins: 25,
    boss: false,
  },

  {
    id: 6,
    title: "Level 6",
    type: "single",
    difficulty: "Anfänger",
    task: "Triff 6x Single 20",
    minArrows: 6,
    maxArrows: 9,
    rewardXP: 45,
    rewardCoins: 30,
    boss: false,
  },

  {
    id: 7,
    title: "Level 7",
    type: "bull",
    difficulty: "Anfänger",
    task: "Triff 1x Bull",
    minArrows: 1,
    maxArrows: 9,
    rewardXP: 50,
    rewardCoins: 30,
    boss: false,
  },

  {
    id: 8,
    title: "Level 8",
    type: "triple",
    difficulty: "Anfänger",
    task: "Triff 1x Triple 20",
    minArrows: 1,
    maxArrows: 9,
    rewardXP: 55,
    rewardCoins: 35,
    boss: false,
  },

  {
    id: 9,
    title: "Level 9",
    type: "checkout",
    difficulty: "Anfänger",
    task: "Checke 40",
    minArrows: 1,
    maxArrows: 9,
    rewardXP: 60,
    rewardCoins: 40,
    boss: false,
  },

  {
    id: 10,
    title: "BOSS",
    type: "boss",
    difficulty: "Anfänger",
    task: "3x Single 20 → 1x Triple 20 → Checke 40",
    minArrows: 5,
    maxArrows: 9,
    rewardXP: 250,
    rewardCoins: 200,
    boss: true,
  },

  {
    id: 11,
    title: "Level 11",
    type: "single",
    difficulty: "Anfänger",
    task: "Triff 3x Single 17",
    minArrows: 3,
    maxArrows: 9,
    rewardXP: 65,
    rewardCoins: 45,
    boss: false,
  },

  {
    id: 12,
    title: "Level 12",
    type: "single",
    difficulty: "Anfänger",
    task: "Triff 3x Single 16",
    minArrows: 3,
    maxArrows: 9,
    rewardXP: 70,
    rewardCoins: 50,
    boss: false,
  },

  {
    id: 13,
    title: "Level 13",
    type: "single",
    difficulty: "Anfänger",
    task: "Triff 3x Single 15",
    minArrows: 3,
    maxArrows: 9,
    rewardXP: 75,
    rewardCoins: 55,
    boss: false,
  },

  {
    id: 14,
    title: "Level 14",
    type: "double",
    difficulty: "Anfänger",
    task: "Triff 2x Doppel 16",
    minArrows: 2,
    maxArrows: 9,
    rewardXP: 80,
    rewardCoins: 60,
    boss: false,
  },

  {
    id: 15,
    title: "Level 15",
    type: "triple",
    difficulty: "Anfänger",
    task: "Triff 2x Triple 20",
    minArrows: 2,
    maxArrows: 9,
    rewardXP: 90,
    rewardCoins: 70,
    boss: false,
  },
]