import {useEffect,useMemo,useState} from 'react'
import {loadTrainingSessions} from '../training/trainingStorage'
import {aggregateCheckoutNumbers} from '../training/trainingGames/randomCheckout'
import '../training/Training.css'

const games=[['201','201'],['bull-finisher','BULL FINISHER'],['random-checkouts','RANDOM CHECKOUTS']]
const pct=(a,b)=>b?`${(a/b*100).toFixed(1)} %`:'–'
const rawOf=row=>(row.player_results??row.playerResults??[])[0]?.rawData??{}
function Card({label,value}){return <div><span>{label}</span><strong>{value}</strong></div>}

export default function Statistics({activeProfile,onBack}){const [sessions,setSessions]=useState([]);const [game,setGame]=useState(null);const [period,setPeriod]=useState('all');const [filter,setFilter]=useState('all');useEffect(()=>{loadTrainingSessions(activeProfile?.id).then(setSessions)},[activeProfile?.id]);const rows=useMemo(()=>sessions.filter(row=>(row.plan??[])[0]?.id===game),[sessions,game]);const visible=period==='current'?rows.slice(0,1):period==='last10'?rows.slice(0,10):rows;const raw=visible.map(rawOf)
 if(!game)return <main className="statistics-screen"><header className="training-page-header"><button onClick={onBack}>‹</button><div><span>DARTQUEST</span><h1>Statistik</h1></div></header><h2>TRAINING</h2><div className="statistics-games">{games.map(([id,label])=><button key={id} onClick={()=>setGame(id)}><span>TRAINING</span><strong>{label}</strong><small>{sessions.filter(row=>(row.plan??[])[0]?.id===id).length} Sessions</small><b>›</b></button>)}</div><h2>KAMPAGNE</h2><p className="statistics-empty">Kampagnenstatistiken bleiben in den bestehenden Kampagnenansichten.</p></main>
 const periodButtons=<div className="statistics-tabs">{[['current','AKTUELL'],['last10','LETZTE 10'],['all','GESAMT']].map(([id,label])=><button key={id} aria-pressed={period===id} onClick={()=>setPeriod(id)}>{label}</button>)}</div>
 let content
 if(game==='201'){const darts=raw.reduce((n,r)=>n+(r.totalDarts||0),0),points=raw.reduce((n,r)=>n+(r.totalPointsScored||0),0),success=raw.reduce((n,r)=>n+(r.successfulRounds||0),0),failed=raw.reduce((n,r)=>n+(r.failedRounds||0),0);content=<><div className="statistics-grid"><Card label="SESSIONS" value={raw.length}/><Card label="AVERAGE" value={darts?(points/darts*3).toFixed(2):'–'}/><Card label="BESTER AVERAGE" value={Math.max(0,...raw.map(r=>r.totalDarts?r.totalPointsScored/r.totalDarts*3:0)).toFixed(2)}/><Card label="HIGHSCORE" value={Math.max(0,...raw.map(r=>r.highestScore||0))}/><Card label="HIGH FINISH" value={Math.max(0,...raw.map(r=>r.highestFinish||0))}/><Card label="ERFOLGSQUOTE" value={pct(success,success+failed)}/><Card label="HÖCHSTER START" value={Math.max(201,...raw.map(r=>r.highestReachedStartValue||201))}/><Card label="Ø DARTS / RUNDE" value={success+failed?(darts/(success+failed)).toFixed(1):'–'}/></div><div className="statistics-trend">{raw.slice(0,10).reverse().map((r,i)=><i key={i} style={{height:`${Math.max(8,Math.min(100,(r.totalDarts?r.totalPointsScored/r.totalDarts*3:0)))}%`}} title="Session Average"/>)}</div></>}
 else if(game==='bull-finisher'){const visits=raw.reduce((n,r)=>n+(r.totalVisits||0),0),darts=raw.reduce((n,r)=>n+(r.totalDarts||0),0),d=raw.reduce((n,r)=>n+(r.directBull3PointCount||0),0),c=raw.reduce((n,r)=>n+(r.checkout2PointCount||0),0),b=raw.reduce((n,r)=>n+(r.rescueBull1PointCount||0),0),z=raw.reduce((n,r)=>n+(r.zeroPointVisitCount||0),0);content=<div className="statistics-grid"><Card label="SESSIONS" value={raw.length}/><Card label="AUFNAHMEN" value={visits}/><Card label="3P DIRECT BULL" value={`${d} · ${pct(d,visits)}`}/><Card label="2P CHECKOUT" value={`${c} · ${pct(c,visits)}`}/><Card label="1P RETTUNG" value={`${b} · ${pct(b,visits)}`}/><Card label="0P" value={`${z} · ${pct(z,visits)}`}/><Card label="Ø DARTS" value={visits?(darts/visits).toFixed(2):'–'}/><Card label="BESTE SESSION" value={Math.max(0,...raw.map(r=>r.points||0))}/></div>}
 else {const attempts=raw.flatMap(r=>r.attempts??[]),success=attempts.filter(a=>a.success),perfect=attempts.filter(a=>a.perfect),numbers=Object.values(aggregateCheckoutNumbers(raw));numbers.sort((a,b)=>filter==='strongest'?b.successes/b.attempts-a.successes/a.attempts:filter==='weakest'?a.successes/a.attempts-b.successes/b.attempts:a.target-b.target);content=<><div className="statistics-grid"><Card label="SESSIONS" value={raw.length}/><Card label="VERSUCHE" value={attempts.length}/><Card label="ERFOLGE" value={success.length}/><Card label="SUCCESS RATE" value={pct(success.length,attempts.length)}/><Card label="PERFEKT" value={perfect.length}/><Card label="PERFECT RATE" value={pct(perfect.length,attempts.length)}/><Card label="HÖCHSTE ZAHL" value={Math.max(0,...success.map(a=>a.target))}/><Card label="Ø DARTS ERFOLG" value={success.length?(success.reduce((n,a)=>n+a.dartsUsed,0)/success.length).toFixed(2):'–'}/></div><h2>CHECKOUT ANALYSE</h2><div className="statistics-tabs">{[['all','ALLE'],['strongest','STÄRKSTE'],['weakest','SCHWÄCHSTE']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="checkout-analysis">{numbers.map(n=><div key={n.target}><strong>{n.target}</strong><span>{n.successes}/{n.attempts} · {pct(n.successes,n.attempts)}</span><small>Perfect {n.perfectCheckouts}</small></div>)}</div></>}
 return <main className="statistics-screen"><header className="training-page-header"><button onClick={()=>setGame(null)}>‹</button><div><span>TRAINING</span><h1>{games.find(g=>g[0]===game)[1]}</h1></div></header>{periodButtons}{content}<h2>LETZTE SESSIONS</h2><div className="statistics-history">{rows.slice(0,10).map(row=><div key={row.id}><span>{new Date(row.created_at).toLocaleDateString('de-DE')}</span><strong>{game==='201'?`${rawOf(row).successes??0} Erfolge`:game==='bull-finisher'?`${rawOf(row).points??0} Punkte`:`${rawOf(row).successes??0}/${rawOf(row).attempts?.length??0}`}</strong></div>)}</div></main>}
