import { useMemo, useState } from 'react'
import { isCampaignLevelUnlocked, loadCampaignProgress, saveCampaignProgress } from './campaignModeStorage'
import { CampaignResult, DartSlots, ScoreKeypad } from './components/CampaignGameUI'
import './CampaignModes.css'

const INPUT_KEY = 'dartquest-checkout-input-mode'
const starsForDarts = (darts) => darts === 1 ? 4 : darts === 2 ? 3 : darts === 3 ? 2 : 1
const freshState = (rest) => ({ rest, darts: 0, visit: [], previousVisit: [], message: '', history: [], result: null })

export default function CheckoutCampaign({ activeProfile, onBack }) {
  const [progress, setProgress] = useState(() => loadCampaignProgress(activeProfile?.id, 'checkout'))
  const [level, setLevel] = useState(null)
  const [mode, setMode] = useState(() => localStorage.getItem(INPUT_KEY) === 'visit' ? 'visit' : 'dart')
  const [state, setState] = useState(() => freshState(2))
  const [value, setValue] = useState('')
  const [checkout, setCheckout] = useState(null)
  const levels = useMemo(() => Array.from({ length: 169 }, (_, index) => index + 1), [])
  const target = level == null ? null : level + 1
  const snap = (current) => ({ rest: current.rest, darts: current.darts, visit: current.visit, previousVisit: current.previousVisit, message: current.message })
  function openLevel(nextLevel) { setLevel(nextLevel); setState(freshState(nextLevel + 1)); setValue(''); setCheckout(null) }
  function changeMode(next) { setMode(next); localStorage.setItem(INPUT_KEY,next); setState(freshState(target)); setValue(''); setCheckout(null) }
  function win(darts) { const stars=starsForDarts(darts); const old=progress.levels[level]||{}; const next={...progress,levels:{...progress.levels,[level]:{completed:true,stars:Math.max(old.stars||0,stars),bestDarts:Math.min(old.bestDarts||Infinity,darts)}}}; setProgress(next); saveCampaignProgress(activeProfile?.id,'checkout',next); setState((current)=>({...current,result:{darts,stars}})); setCheckout(null); setValue('') }
  function addDart(points) { if (!Number.isInteger(points)||points<0||points>60||state.result) return; const remainder=state.rest-points; if(remainder===0){setCheckout({darts:state.darts+1});return} const bust=remainder<0||remainder===1; const visit=[...state.visit,bust?'Bust':points]; const end=visit.length===3||bust; setState({...state,rest:bust?state.rest:remainder,darts:state.darts+1,visit:end?[]:visit,previousVisit:end?visit:state.previousVisit,message:end?'Aufnahme beendet. Du kannst mit der nächsten Aufnahme fortfahren.':'',history:[...state.history,snap(state)]});setValue('') }
  function addVisit(){const points=Number(value);if(!Number.isInteger(points)||points<0||points>180)return;const remainder=state.rest-points;if(remainder===0){setCheckout({visitMode:true});return}const bust=remainder<0||remainder===1;setState({...state,rest:bust?state.rest:remainder,darts:state.darts+3,visit:[],previousVisit:[bust?'Bust':points],message:bust?'Bust – der Restscore bleibt bestehen.':'',history:[...state.history,snap(state)]});setValue('')}
  function reject(){const added=checkout.visitMode?3:1;setState({...state,darts:state.darts+added,visit:[],previousVisit:['Bust'],message:'Bust – der Restscore bleibt bestehen.',history:[...state.history,snap(state)]});setCheckout(null);setValue('')}
  function undo(){const previous=state.history.at(-1);if(!previous)return;setState({...state,...previous,history:state.history.slice(0,-1)});setValue('');setCheckout(null)}
  if(level!=null)return <main className="checkout-play"><header><button type="button" onClick={()=>setLevel(null)}>‹</button><div><span>CHECKOUT · LEVEL {level}</span><h1>Rest: {state.rest}</h1></div><button className="checkout-undo" type="button" disabled={!state.history.length} onClick={undo}>↶ Undo</button></header><nav className="checkout-mode"><button className={mode==='dart'?'active':''} onClick={()=>changeMode('dart')}>PRO DART</button><button className={mode==='visit'?'active':''} onClick={()=>changeMode('visit')}>PRO AUFNAHME</button></nav><DartSlots values={state.visit.length?state.visit:state.previousVisit}/><div className="checkout-meta">{state.darts} Darts gesamt · Ausgangsrest {target}</div>{state.message&&<p className="campaign-notice">{state.message}</p>}{!state.result&&mode==='dart'&&<section className="checkout-entry"><label>Punkte des nächsten Darts<input inputMode="numeric" value={value} onChange={(event)=>setValue(event.target.value.replace(/\D/g,'').slice(0,2))}/></label><div><button onClick={()=>addDart(0)}>NICHT GETROFFEN</button><button disabled={value===''||Number(value)>60} onClick={()=>addDart(Number(value))}>DART WERTEN</button></div></section>}{!state.result&&mode==='visit'&&<ScoreKeypad value={value} onChange={setValue} onConfirm={addVisit}/>} {checkout&&<div className="checkout-dialog"><section role="dialog" aria-modal="true"><h2>Regelkonform mit einem Doppel ausgecheckt?</h2><p>Mit welchem Dart wurde ausgecheckt?</p><div className="checkout-dart-choice">{[1,2,3].map((dart)=><button key={dart} onClick={()=>win(checkout.visitMode?state.darts+dart:checkout.darts)}>{dart} Dart{dart>1?'s':''}</button>)}</div><button onClick={reject}>NEIN · BUST</button></section></div>}{state.result&&<CampaignResult title="Checkout geschafft"><p>{state.result.darts} Darts</p><strong className="result-stars">{'★'.repeat(state.result.stars)}{'☆'.repeat(4-state.result.stars)}</strong><button disabled={level>=169} onClick={()=>openLevel(level+1)}>{level>=169?'KAMPAGNE ABGESCHLOSSEN':'NÄCHSTE AUFGABE'}</button><button onClick={()=>setLevel(null)}>ZUR LEVELAUSWAHL</button></CampaignResult>}</main>
  const completed=Object.values(progress.levels).filter((item)=>item.completed).length
  return <main className="campaign-levels"><header><button onClick={onBack}>‹</button><div><span>CHECKOUT-KAMPAGNE</span><h1>169 Checkouts</h1></div></header><p>{completed}/169 abgeschlossen</p><div className="campaign-level-grid">{levels.map((item)=>{const unlocked=isCampaignLevelUnlocked(progress,item),result=progress.levels[item];return <button key={item} disabled={!unlocked} onClick={()=>openLevel(item)}><strong>{unlocked?item:'🔒'}</strong><span>Checkout {item+1}</span><small>{result?.stars?'★'.repeat(result.stars):'☆☆☆☆'}{result?.bestDarts?` · ${result.bestDarts} Darts`:''}</small></button>})}</div></main>
}
