import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {create201State,get201Average,get201CheckoutDartCounts,record201Visit} from '../src/features/training/trainingGames/game201.js'
import {createBullFinisherState,recordBullFinisherVisit} from '../src/features/training/trainingGames/bullFinisher.js'
import {advanceRandomCheckoutVisit,aggregateCheckoutNumbers,createRandomCheckoutState,generateCheckoutTarget,getCheckoutPool,getRandomCheckoutDartOptions,isCheckoutPossibleWithinDarts,randomCheckoutSummary,recordRandomCheckout} from '../src/features/training/trainingGames/randomCheckout.js'
import {getMinimumCheckoutDarts,isBust} from '../src/features/training/trainingGames/checkoutMath.js'
import {TRAINING_TEMPLATES,createTrainingTask,moveTrainingTask,updateTrainingTaskAt} from '../src/features/training/trainingTemplates.js'
import {TRAINING_INFO,getTrainingInfo} from '../src/features/training/trainingInfo.js'

test('visible library contains exactly the three fixed games',()=>assert.deepEqual(TRAINING_TEMPLATES.map(x=>x.id),['201','bull-finisher','random-checkouts']))
test('201 succeeds on dart 12 and raises the next start',()=>{let s=create201State({dartLimit:12,successGoal:5});s=record201Visit(s,{score:180,darts:3});for(let i=0;i<2;i++)s=record201Visit(s,{score:0,darts:3});s=record201Visit(s,{score:21,darts:3,checkout:true});assert.equal(s.successes,1);assert.equal(s.startValue,211)})
test('201 normal X01 visits count three darts and checkout counts exact darts',()=>{let s=create201State({dartLimit:12,successGoal:5});s=record201Visit(s,{score:60});assert.deepEqual([s.remaining,s.dartsThisRound],[141,3]);s=record201Visit(s,{score:45});assert.deepEqual([s.remaining,s.dartsThisRound],[96,6]);s=record201Visit(s,{score:56});assert.deepEqual([s.remaining,s.dartsThisRound],[40,9]);s=record201Visit(s,{score:40,darts:2,checkout:true});assert.equal(s.rounds[0].dartsUsed,11);assert.equal(s.successes,1);assert.equal(s.startValue,211)})
test('201 nine-dart controller records 60, 81 and a two-dart finish as eight darts',()=>{let s=create201State({dartLimit:9,successGoal:5});s=record201Visit(s,{score:60});s=record201Visit(s,{score:81});s=record201Visit(s,{score:60,darts:2,checkout:true});assert.deepEqual([s.successes,s.startValue,s.rounds[0].dartsUsed,s.visits.length],[1,211,8,3])})
test('201 exposes only checkout darts still inside the limit',()=>{const s={...create201State({dartLimit:12}),remaining:40,dartsThisRound:11};assert.deepEqual(get201CheckoutDartCounts(s),[1]);const done=record201Visit(s,{score:40,darts:1,checkout:true});assert.equal(done.rounds[0].dartsUsed,12);assert.equal(done.successes,1)})
test('201 failure floors at 201 and reduces higher starts',()=>{let s=create201State({dartLimit:12});for(let i=0;i<4;i++)s=record201Visit(s,{score:0,darts:3});assert.equal(s.startValue,201);s={...s,startValue:221,remaining:221};for(let i=0;i<4;i++)s=record201Visit(s,{score:0,darts:3});assert.equal(s.startValue,211);s={...s,startValue:211,remaining:211};for(let i=0;i<4;i++)s=record201Visit(s,{score:0,darts:3});assert.equal(s.startValue,201)})
test('201 bust and average use scored raw points',()=>{let s=create201State();s=record201Visit(s,{score:180});s=record201Visit(s,{score:180});assert.equal(s.remaining,21);s=record201Visit(s,{score:20});assert.equal(s.remaining,21);assert.equal(isBust(21,20,false),true);assert.equal(get201Average(s),60)})
test('double-out math includes Bull and known minima',()=>{assert.equal(getMinimumCheckoutDarts(40),1);assert.equal(getMinimumCheckoutDarts(50),1);assert.equal(getMinimumCheckoutDarts(51),2);assert.equal(getMinimumCheckoutDarts(170),3);assert.equal(isBust(50,50,true),false)})
test('Bull Finisher awards 3, 2, 1 and 0 and ends at 20',()=>{let s=createBullFinisherState();for(const kind of ['direct','checkout','rescue','miss'])s=recordBullFinisherVisit(s,kind);assert.deepEqual([s.points,s.directBull3PointCount,s.checkout2PointCount,s.rescueBull1PointCount,s.zeroPointVisitCount],[6,1,1,1,1]);while(!s.complete)s=recordBullFinisherVisit(s,'direct');assert.ok(s.points>=20)})
test('random generator stays in range, is reachable and avoids repeats',()=>{for(const c of [{from:2,to:60,maxVisits:1},{from:40,to:100,maxVisits:2},{from:81,to:170,maxVisits:3}]){const pool=getCheckoutPool(c);assert.ok(pool.every(x=>x>=c.from&&x<=c.to));const first=generateCheckoutTarget(c,null,()=>0);const second=generateCheckoutTarget(c,first,()=>0);if(pool.length>1)assert.notEqual(first,second)}})
test('random records perfect and per-number raw aggregates',()=>{let s=createRandomCheckoutState({from:40,to:40,maxVisits:1},()=>0);s=recordRandomCheckout(s,{success:true,dartsUsed:1},()=>0);s=recordRandomCheckout(s,{success:true,dartsUsed:2},()=>0);s=recordRandomCheckout(s,{success:false,dartsUsed:3},()=>0);assert.equal(s.perfectCheckouts,1);const row=aggregateCheckoutNumbers([s])[40];assert.deepEqual([row.attempts,row.successes,row.failures,row.perfectCheckouts,row.bestDarts],[3,2,1,1,1])})
test('random dart buttons follow mathematical minimum checkout darts',()=>{for(const [target,options] of [[3,[2,3]],[40,[1,2,3]],[41,[2,3]],[50,[1,2,3]],[110,[2,3]],[170,[3]]]){const s=createRandomCheckoutState({from:target,to:target,maxVisits:1},()=>0);assert.deepEqual(getRandomCheckoutDartOptions(s),options)}})
test('one-visit generator excludes every three-dart bogey',()=>{const pool=getCheckoutPool({from:2,to:170,maxVisits:1});for(const bogey of [159,162,163,165,166,168,169])assert.equal(pool.includes(bogey),false);assert.equal(isCheckoutPossibleWithinDarts(170,3),true)})
test('checkout-count goal ends after exactly twenty tasks with comparable rates',()=>{let s=createRandomCheckoutState({from:40,to:40,maxVisits:1,goalType:'checkoutCount',targetCheckoutCount:20},()=>0);for(let i=0;i<20;i++)s=recordRandomCheckout(s,{success:i<14,dartsUsed:i<14?1:3},()=>0);assert.equal(s.complete,true);assert.equal(s.attempts.length,20);assert.deepEqual(randomCheckoutSummary(s),{goalType:'checkoutCount',durationMinutes:null,targetCheckoutCount:20,totalTasks:20,successes:14,failures:6,perfectCheckouts:14,successRate:70,perfectRate:70})})
test('multiple visits accumulate total darts without nine permanent buttons',()=>{let s=createRandomCheckoutState({from:159,to:159,maxVisits:2},()=>0);s=advanceRandomCheckoutVisit(s,()=>0);assert.equal(s.currentVisit,2);s=recordRandomCheckout(s,{success:true,dartsUsed:2},()=>0);assert.equal(s.attempts[0].dartsUsed,5);assert.equal(s.attempts[0].totalDartsUsed,5);assert.equal(s.attempts[0].minimumDarts,getMinimumCheckoutDarts(159,6))})
test('perfect uses theoretical minimum rather than selected button alone',()=>{let three=createRandomCheckoutState({from:3,to:3,maxVisits:1},()=>0);three=recordRandomCheckout(three,{success:true,dartsUsed:2},()=>0);assert.equal(three.attempts[0].perfect,true);three=createRandomCheckoutState({from:3,to:3,maxVisits:1},()=>0);three=recordRandomCheckout(three,{success:true,dartsUsed:3},()=>0);assert.equal(three.attempts[0].perfect,false);let forty=createRandomCheckoutState({from:40,to:40,maxVisits:1},()=>0);forty=recordRandomCheckout(forty,{success:true,dartsUsed:1},()=>0);assert.equal(forty.attempts[0].perfect,true)})
test('random UI has goal modes, compact layout and integrates with the shared plan builder',()=>{const game=readFileSync(new URL('../src/features/training/Training.jsx',import.meta.url),'utf8');assert.match(game,/TRAININGSZIEL/);assert.match(game,/goalType==='checkoutCount'/);assert.match(game,/is-random-checkout/);assert.match(game,/getRandomCheckoutDartOptions/);assert.match(game,/actionLabel=\{editing\.index==null\?'HINZUFÜGEN':'SPEICHERN'\}/)})
test('solo-only persistence and navigation are wired',()=>{const storage=readFileSync(new URL('../src/features/training/trainingStorage.js',import.meta.url),'utf8');const game=readFileSync(new URL('../src/features/training/Training.jsx',import.meta.url),'utf8');const home=readFileSync(new URL('../src/features/home/Home.jsx',import.meta.url),'utf8');const profile=readFileSync(new URL('../src/features/profile/Profile.jsx',import.meta.url),'utf8');assert.match(game,/players\.length===1/);assert.match(storage,/eq\('mode', 'solo'\)/);assert.match(home,/>Statistik</);assert.match(profile,/>Sammelkarten</)})
test('201 reuses the full Rival ScoreKeypad including quick scores and checkout behavior',()=>{const game=readFileSync(new URL('../src/features/training/Training.jsx',import.meta.url),'utf8');assert.match(game,/<ScoreKeypad value=\{score\}/);assert.doesNotMatch(game,/quick=\{\[\]\}/);assert.match(game,/checkoutDartCounts=\{get201CheckoutDartCounts\(state\)\}/);assert.match(game,/onCheckoutLongPress=\{checkout201\}/);assert.doesNotMatch(game,/>DOUBLE OUT<\/button>/)})
test('201 goals are exactly 5, 10 and 20 in the builder',()=>{const game=readFileSync(new URL('../src/features/training/Training.jsx',import.meta.url),'utf8');assert.match(game,/successGoal} values=\{\[5,10,20\]\}/);assert.doesNotMatch(game,/successGoal} values=\{\[3,5,10\]\}/)})
test('training plan keeps add order, supports moves and preserves order while editing',()=>{const first=createTrainingTask('201'),second=createTrainingTask('bull-finisher'),third=createTrainingTask('random-checkouts');const plan=[first,second,third];const moved=moveTrainingTask(plan,2,-1);assert.deepEqual(moved.map(item=>item.id),['201','random-checkouts','bull-finisher']);const edited=createTrainingTask('201',{configuration:{dartLimit:9,successGoal:10}});const updated=updateTrainingTaskAt(moved,0,edited);assert.deepEqual(updated.map(item=>item.id),['201','random-checkouts','bull-finisher']);assert.deepEqual(updated[0].configuration,{dartLimit:9,successGoal:10})})
test('builder renders the three games directly, editable bottom plan and sorting',()=>{const game=readFileSync(new URL('../src/features/training/Training.jsx',import.meta.url),'utf8');assert.match(game,/VERFÜGBARE ÜBUNGEN/);assert.match(game,/TRAINING_TEMPLATES\.map/);assert.doesNotMatch(game,/training-add-button/);assert.doesNotMatch(game,/pickerOpen/);assert.match(game,/training-builder-bottom/);assert.match(game,/DEIN TRAININGSPLAN/);assert.match(game,/move\(index,-1\)/);assert.match(game,/move\(index,1\)/);assert.match(game,/TRAINING STARTEN/)})
test('201 main score and REST use the same remaining source of truth',()=>{const game=readFileSync(new URL('../src/features/training/Training.jsx',import.meta.url),'utf8');assert.match(game,/className="training-target">\{state\.remaining\}/);assert.match(game,/<span>REST<\/span><strong>\{state\.remaining\}/);assert.match(game,/STUFE \$\{state\.startValue\}/)})
test('201 keypad uses the Rival mobile proportions and stays in the thumb zone',()=>{const css=readFileSync(new URL('../src/features/training/Training.css',import.meta.url),'utf8');assert.match(css,/\.training-game-main\.is-201 \.score-keypad\s*\{[^}]*height:\s*clamp\(270px, 42dvh, 340px\)/s);assert.match(css,/grid-template-rows:\s*43px repeat\(2,minmax\(36px,1fr\)\) repeat\(5,minmax\(38px,1fr\)\)/);assert.match(css,/\.training-game-main\.is-201 \.score-keypad\s*\{[^}]*margin-top:\s*auto/s)})
test('plan scroll wrapper is not styled as a plan row',()=>{const css=readFileSync(new URL('../src/features/training/Training.css',import.meta.url),'utf8');assert.doesNotMatch(css,/\.training-plan\s*>\s*div\s*\{/);assert.match(css,/\.training-plan-entry\s*\{[^}]*display:\s*grid/s);assert.match(css,/\.training-plan-scroll\s*\{[^}]*overflow-y:\s*auto/s)})
test('training opens the exercise builder directly without an intermediate landing page',()=>{const game=readFileSync(new URL('../src/features/training/Training.jsx',import.meta.url),'utf8');assert.match(game,/useState\('builder'\)/);assert.match(game,/return <Builder onBack=\{onBack\}/);assert.doesNotMatch(game,/className="training-home"/);assert.doesNotMatch(game,/TRAINING ERSTELLEN/)})
test('every training template has data-driven information',()=>{assert.deepEqual(Object.keys(TRAINING_INFO),TRAINING_TEMPLATES.map(template=>template.id));for(const template of TRAINING_TEMPLATES){const info=getTrainingInfo(template.id);assert.equal(info.title,template.title);assert.ok(info.subtitle);assert.ok(info.sections.length)}})
test('Bull Finisher info explains that Bull on dart three is rescue-only',()=>{const info=getTrainingInfo('bull-finisher');const copy=JSON.stringify(info);assert.match(info.subtitle,/Rettungswurf/);assert.match(copy,/DART 3 GEHT NICHT AUTOMATISCH AUFS BULL/);assert.match(copy,/noch ein regulärer Checkout mit einem Dart möglich/);assert.match(copy,/kein regulärer Checkout mit dem letzten Dart mehr möglich/)})
test('exercise info uses a separate button and one reusable read-only modal',()=>{const builder=readFileSync(new URL('../src/features/training/Training.jsx',import.meta.url),'utf8');const modal=readFileSync(new URL('../src/features/training/TrainingInfoModal.jsx',import.meta.url),'utf8');assert.match(builder,/className="training-template-info"/);assert.match(builder,/onClick=\{\(\)=>setInfoId\(template\.id\)\}/);assert.match(builder,/<TrainingInfoModal templateId=\{infoId\}/);assert.match(modal,/role="dialog"/);assert.match(modal,/VERSTANDEN/);assert.match(modal,/event\.key==='Escape'/);assert.doesNotMatch(modal,/setSelected|toggle\(|onStart/)})
test('training session table has owner RLS',()=>{const sql=readFileSync(new URL('../supabase/migrations/20260907062651_training_sessions.sql',import.meta.url),'utf8');assert.match(sql,/enable row level security/);assert.match(sql,/auth\.uid\(\)\) = user_id/);assert.match(sql,/training_sessions_user_created_idx/)})
