function buildTargets(entries, targetType) {
  const targets = new Map()
  entries.forEach((value) => {
    const normalized = String(value).trim()
    const id = targetType === 'number' ? `number:${normalized}` : normalized.toUpperCase()
    const existing = targets.get(id)
    if (existing) {
      existing.requiredHits += 1
      return
    }
    targets.set(id, {
      id,
      label: normalized.toUpperCase() === 'BULL' ? 'Bull' : normalized,
      targetType,
      ...(targetType === 'number' ? { targetValue: Number(normalized) } : {}),
      requiredHits: 1,
    })
  })
  return [...targets.values()]
}

function numberTargets(...numbers) {
  return buildTargets(numbers, 'number')
}

function fieldTargets(...fields) {
  return buildTargets(fields, 'field')
}

export const beginnerLevels = [
  {
    id: 1,
    world: 1,
    title: 'Treffe 20',
    task: 'Treffe 20',
    targets: numberTargets(20),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 20,
    rewardCoins: 10,
  },

  {
    id: 2,
    world: 1,
    title: 'Treffe 3',
    task: 'Treffe 3',
    targets: numberTargets(3),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 20,
    rewardCoins: 10,
  },

  {
    id: 3,
    world: 1,
    title: 'Treffe 11',
    task: 'Treffe 11',
    targets: numberTargets(11),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 20,
    rewardCoins: 10,
  },

  {
    id: 4,
    world: 1,
    title: 'Treffe 6',
    task: 'Treffe 6',
    targets: numberTargets(6),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 20,
    rewardCoins: 10,
  },

  {
    id: 5,
    world: 1,
    title: 'Treffe 20',
    task: 'Treffe 20',
    targets: numberTargets(20),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 20,
    rewardCoins: 10,
  },

  {
    id: 6,
    world: 1,
    title: 'Treffe 3',
    task: 'Treffe 3',
    targets: numberTargets(3),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 20,
    rewardCoins: 10,
  },

  {
    id: 7,
    world: 1,
    title: 'Treffe 11',
    task: 'Treffe 11',
    targets: numberTargets(11),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 20,
    rewardCoins: 10,
  },

  {
    id: 8,
    world: 1,
    title: 'Treffe 6',
    task: 'Treffe 6',
    targets: numberTargets(6),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 20,
    rewardCoins: 10,
  },

  {
    id: 9,
    world: 1,
    title: 'Treffe 20, 3',
    task: 'Treffe 20, 3',
    targets: numberTargets(20, 3),
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 25,
    rewardCoins: 12,
  },

  {
    id: 10,
    world: 1,
    title: 'Boss – Treffe 20, 20, 20',
    task: 'Treffe 20, 20, 20',
    targets: numberTargets(20, 20, 20),
    targetHits: 3,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: true,
    rewardXP: 80,
    rewardCoins: 50,
  },

  {
    id: 11,
    world: 2,
    title: 'Treffe 20, 20',
    task: 'Treffe 20, 20',
    targets: numberTargets(20, 20),
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 22,
    rewardCoins: 11,
  },

  {
    id: 12,
    world: 2,
    title: 'Treffe 3, 3',
    task: 'Treffe 3, 3',
    targets: numberTargets(3, 3),
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 22,
    rewardCoins: 11,
  },

  {
    id: 13,
    world: 2,
    title: 'Treffe 11, 11',
    task: 'Treffe 11, 11',
    targets: numberTargets(11, 11),
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 25,
    rewardCoins: 12,
  },

  {
    id: 14,
    world: 2,
    title: 'Treffe 6, 6',
    task: 'Treffe 6, 6',
    targets: numberTargets(6, 6),
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 25,
    rewardCoins: 12,
  },

  {
    id: 15,
    world: 2,
    title: 'Treffe Bull',
    task: 'Treffe Bull',
    targets: fieldTargets('Bull'),
    targetHits: 1,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 25,
    rewardCoins: 12,
  },

  {
    id: 16,
    world: 2,
    title: 'Treffe 1, 5',
    task: 'Treffe 1, 5',
    targets: numberTargets(1, 5),
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 25,
    rewardCoins: 12,
  },

  {
    id: 17,
    world: 2,
    title: 'Treffe 19, 17',
    task: 'Treffe 19, 17',
    targets: numberTargets(19, 17),
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 25,
    rewardCoins: 12,
  },

  {
    id: 18,
    world: 2,
    title: 'Treffe 14, 8',
    task: 'Treffe 14, 8',
    targets: numberTargets(14, 8),
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 28,
    rewardCoins: 14,
  },

  {
    id: 19,
    world: 2,
    title: 'Treffe 13, 1',
    task: 'Treffe 13, 1',
    targets: numberTargets(13, 1),
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 28,
    rewardCoins: 14,
  },

  {
    id: 20,
    world: 2,
    title: 'Boss – Treffe 20, 3, 11, 6',
    task: 'Treffe 20, 3, 11, 6',
    targets: numberTargets(20, 3, 11, 6),
    targetHits: 4,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: true,
    rewardXP: 90,
    rewardCoins: 55,
  },

  {
    id: 21,
    world: 3,
    title: 'Treffe 16 → 8',
    task: 'Treffe 16 → 8',
    targets: numberTargets(16, 8),
    orderedTargets: true,
    sequence: ['number:16', 'number:8'],
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 30,
    rewardCoins: 15,
  },

  {
    id: 22,
    world: 3,
    title: 'Treffe 8 → 4',
    task: 'Treffe 8 → 4',
    targets: numberTargets(8, 4),
    orderedTargets: true,
    sequence: ['number:8', 'number:4'],
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 30,
    rewardCoins: 15,
  },

  {
    id: 23,
    world: 3,
    title: 'Treffe 4 → 2',
    task: 'Treffe 4 → 2',
    targets: numberTargets(4, 2),
    orderedTargets: true,
    sequence: ['number:4', 'number:2'],
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 30,
    rewardCoins: 15,
  },

  {
    id: 24,
    world: 3,
    title: 'Treffe 2 → 1',
    task: 'Treffe 2 → 1',
    targets: numberTargets(2, 1),
    orderedTargets: true,
    sequence: ['number:2', 'number:1'],
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 30,
    rewardCoins: 15,
  },

  {
    id: 25,
    world: 3,
    title: 'Treffe 20 → 10',
    task: 'Treffe 20 → 10',
    targets: numberTargets(20, 10),
    orderedTargets: true,
    sequence: ['number:20', 'number:10'],
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 30,
    rewardCoins: 15,
  },

  {
    id: 26,
    world: 3,
    title: 'Treffe 10 → 5',
    task: 'Treffe 10 → 5',
    targets: numberTargets(10, 5),
    orderedTargets: true,
    sequence: ['number:10', 'number:5'],
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 32,
    rewardCoins: 16,
  },

  {
    id: 27,
    world: 3,
    title: 'Treffe 5 → 1',
    task: 'Treffe 5 → 1',
    targets: numberTargets(5, 1),
    orderedTargets: true,
    sequence: ['number:5', 'number:1'],
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 32,
    rewardCoins: 16,
  },

  {
    id: 28,
    world: 3,
    title: 'Erziele mindestens 26 Punkte mit 3 Darts',
    task: 'Erziele mindestens 26 Punkte mit 3 Darts',
    scoreTarget: 26,
    scoreDarts: 3,
    targetHits: null,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 35,
    rewardCoins: 18,
  },

  {
    id: 29,
    world: 3,
    title: 'Treffe 20, 20, 20',
    task: 'Treffe 20, 20, 20',
    targets: numberTargets(20, 20, 20),
    targetHits: 3,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 35,
    rewardCoins: 18,
  },

  {
    id: 30,
    world: 3,
    title: 'Boss – Treffe 20 → 10 → 5 → 1',
    task: 'Treffe 20 → 10 → 5 → 1',
    targets: numberTargets(20, 10, 5, 1),
    orderedTargets: true,
    sequence: ['number:20', 'number:10', 'number:5', 'number:1'],
    targetHits: 4,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: true,
    rewardXP: 100,
    rewardCoins: 60,
  },

  {
    id: 31,
    world: 4,
    title: 'Treffe 12 → 6',
    task: 'Treffe 12 → 6',
    targets: numberTargets(12, 6),
    orderedTargets: true,
    sequence: ['number:12', 'number:6'],
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 35,
    rewardCoins: 18,
  },

  {
    id: 32,
    world: 4,
    title: 'Treffe 6 → 3',
    task: 'Treffe 6 → 3',
    targets: numberTargets(6, 3),
    orderedTargets: true,
    sequence: ['number:6', 'number:3'],
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 35,
    rewardCoins: 18,
  },

  {
    id: 33,
    world: 4,
    title: 'Treffe 3 → 1',
    task: 'Treffe 3 → 1',
    targets: numberTargets(3, 1),
    orderedTargets: true,
    sequence: ['number:3', 'number:1'],
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 35,
    rewardCoins: 18,
  },

  {
    id: 34,
    world: 4,
    title: 'Treffe 12, 12',
    task: 'Treffe 12, 12',
    targets: numberTargets(12, 12),
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 38,
    rewardCoins: 19,
  },

  {
    id: 35,
    world: 4,
    title: 'Erziele mindestens 30 Punkte mit 3 Darts',
    task: 'Erziele mindestens 30 Punkte mit 3 Darts',
    scoreTarget: 30,
    scoreDarts: 3,
    targetHits: null,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 38,
    rewardCoins: 19,
  },

  {
    id: 36,
    world: 4,
    title: 'Treffe 16 → 8',
    task: 'Treffe 16 → 8',
    targets: numberTargets(16, 8),
    orderedTargets: true,
    sequence: ['number:16', 'number:8'],
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 42,
    rewardCoins: 21,
  },

  {
    id: 37,
    world: 4,
    title: 'Treffe 8 → 4',
    task: 'Treffe 8 → 4',
    targets: numberTargets(8, 4),
    orderedTargets: true,
    sequence: ['number:8', 'number:4'],
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 42,
    rewardCoins: 21,
  },

  {
    id: 38,
    world: 4,
    title: 'Treffe 20 → 10',
    task: 'Treffe 20 → 10',
    targets: numberTargets(20, 10),
    orderedTargets: true,
    sequence: ['number:20', 'number:10'],
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 45,
    rewardCoins: 22,
  },

  {
    id: 39,
    world: 4,
    title: 'Treffe 10 → 5',
    task: 'Treffe 10 → 5',
    targets: numberTargets(10, 5),
    orderedTargets: true,
    sequence: ['number:10', 'number:5'],
    targetHits: 2,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 48,
    rewardCoins: 24,
  },

  {
    id: 40,
    world: 4,
    title: 'Boss – Treffe 16 → 8 → 4 → 2',
    task: 'Treffe 16 → 8 → 4 → 2',
    targets: numberTargets(16, 8, 4, 2),
    orderedTargets: true,
    sequence: ['number:16', 'number:8', 'number:4', 'number:2'],
    targetHits: 4,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: true,
    rewardXP: 110,
    rewardCoins: 65,
  },

  {
    id: 41,
    world: 5,
    title: 'Treffe 1 → 18',
    task: 'Treffe 1 → 18',
    targets: numberTargets(1, 18),
    orderedTargets: true,
    sequence: ['number:1', 'number:18'],
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 40,
    rewardCoins: 20,
  },

  {
    id: 42,
    world: 5,
    title: 'Treffe 4 → 13',
    task: 'Treffe 4 → 13',
    targets: numberTargets(4, 13),
    orderedTargets: true,
    sequence: ['number:4', 'number:13'],
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 40,
    rewardCoins: 20,
  },

  {
    id: 43,
    world: 5,
    title: 'Treffe 6 → 10',
    task: 'Treffe 6 → 10',
    targets: numberTargets(6, 10),
    orderedTargets: true,
    sequence: ['number:6', 'number:10'],
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 40,
    rewardCoins: 20,
  },

  {
    id: 44,
    world: 5,
    title: 'Treffe 15 → 2',
    task: 'Treffe 15 → 2',
    targets: numberTargets(15, 2),
    orderedTargets: true,
    sequence: ['number:15', 'number:2'],
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 40,
    rewardCoins: 20,
  },

  {
    id: 45,
    world: 5,
    title: 'Treffe 17 → 3',
    task: 'Treffe 17 → 3',
    targets: numberTargets(17, 3),
    orderedTargets: true,
    sequence: ['number:17', 'number:3'],
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 42,
    rewardCoins: 21,
  },

  {
    id: 46,
    world: 5,
    title: 'Treffe 19 → 7',
    task: 'Treffe 19 → 7',
    targets: numberTargets(19, 7),
    orderedTargets: true,
    sequence: ['number:19', 'number:7'],
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 45,
    rewardCoins: 22,
  },

  {
    id: 47,
    world: 5,
    title: 'Treffe 16 → 8',
    task: 'Treffe 16 → 8',
    targets: numberTargets(16, 8),
    orderedTargets: true,
    sequence: ['number:16', 'number:8'],
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 45,
    rewardCoins: 22,
  },

  {
    id: 48,
    world: 5,
    title: 'Treffe 11 → 14',
    task: 'Treffe 11 → 14',
    targets: numberTargets(11, 14),
    orderedTargets: true,
    sequence: ['number:11', 'number:14'],
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 48,
    rewardCoins: 24,
  },

  {
    id: 49,
    world: 5,
    title: 'Treffe 9 → 12',
    task: 'Treffe 9 → 12',
    targets: numberTargets(9, 12),
    orderedTargets: true,
    sequence: ['number:9', 'number:12'],
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 50,
    rewardCoins: 25,
  },

  {
    id: 50,
    world: 5,
    title: 'Boss – Treffe 5 → 20 → Bull',
    task: 'Treffe 5 → 20 → Bull',
    targets: fieldTargets('5', '20', 'Bull'),
    orderedTargets: true,
    sequence: ['number:5', 'number:20', 'BULL'],
    targetHits: 3,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: true,
    rewardXP: 120,
    rewardCoins: 70,
  },

  {
    id: 51,
    world: 6,
    title: 'Erziele mindestens 40 Punkte',
    task: 'Erziele mindestens 40 Punkte',
    scoreTarget: 40,
    scoreDarts: 3,
    targetHits: null,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 45,
    rewardCoins: 22,
  },

  {
    id: 52,
    world: 6,
    title: 'Treffe S20 → S10 → S5',
    task: 'Treffe S20 → S10 → S5',
    targets: fieldTargets('S20', 'S10', 'S5'),
    orderedTargets: true,
    sequence: ['S20', 'S10', 'S5'],
    targetHits: 3,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 45,
    rewardCoins: 22,
  },

  {
    id: 53,
    world: 6,
    title: 'Treffe S16 → S8 → S4',
    task: 'Treffe S16 → S8 → S4',
    targets: fieldTargets('S16', 'S8', 'S4'),
    orderedTargets: true,
    sequence: ['S16', 'S8', 'S4'],
    targetHits: 3,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 48,
    rewardCoins: 24,
  },

  {
    id: 54,
    world: 6,
    title: 'Erziele mindestens 50 Punkte',
    task: 'Erziele mindestens 50 Punkte',
    scoreTarget: 50,
    scoreDarts: 3,
    targetHits: null,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 48,
    rewardCoins: 24,
  },

  {
    id: 55,
    world: 6,
    title: 'Treffe S12 → S6 → S3',
    task: 'Treffe S12 → S6 → S3',
    targets: fieldTargets('S12', 'S6', 'S3'),
    orderedTargets: true,
    sequence: ['S12', 'S6', 'S3'],
    targetHits: 3,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 50,
    rewardCoins: 25,
  },

  {
    id: 56,
    world: 6,
    title: 'Treffe S4 → S2 → S1',
    task: 'Treffe S4 → S2 → S1',
    targets: fieldTargets('S4', 'S2', 'S1'),
    orderedTargets: true,
    sequence: ['S4', 'S2', 'S1'],
    targetHits: 3,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 52,
    rewardCoins: 26,
  },

  {
    id: 57,
    world: 6,
    title: 'Treffe S20, S3',
    task: 'Treffe S20, S3',
    targets: fieldTargets('S20', 'S3'),
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 55,
    rewardCoins: 28,
  },

  {
    id: 58,
    world: 6,
    title: 'Treffe S11, S6',
    task: 'Treffe S11, S6',
    targets: fieldTargets('S11', 'S6'),
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 55,
    rewardCoins: 28,
  },

  {
    id: 59,
    world: 6,
    title: 'Erziele mindestens 60 Punkte',
    task: 'Erziele mindestens 60 Punkte',
    scoreTarget: 60,
    scoreDarts: 3,
    targetHits: null,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 58,
    rewardCoins: 29,
  },

  {
    id: 60,
    world: 6,
    title: 'Boss – Treffe S20 → S10 → S5 → S16 → S8 → S4',
    task: 'Treffe S20 → S10 → S5 → S16 → S8 → S4',
    targets: fieldTargets('S20', 'S10', 'S5', 'S16', 'S8', 'S4'),
    orderedTargets: true,
    sequence: ['S20', 'S10', 'S5', 'S16', 'S8', 'S4'],
    targetHits: 6,
    starVisitThresholds: { four: 3, three: 5, two: 7 },
    perfectDarts: 9,
    boss: true,
    rewardXP: 140,
    rewardCoins: 80,
  },

  {
    id: 61,
    world: 7,
    title: 'Treffe S16, S16',
    task: 'Treffe S16, S16',
    targets: fieldTargets('S16', 'S16'),
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 55,
    rewardCoins: 28,
  },

  {
    id: 62,
    world: 7,
    title: 'Treffe D16',
    task: 'Treffe D16',
    targets: fieldTargets('D16'),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 55,
    rewardCoins: 28,
  },

  {
    id: 63,
    world: 7,
    title: 'Treffe S8, S8',
    task: 'Treffe S8, S8',
    targets: fieldTargets('S8', 'S8'),
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 55,
    rewardCoins: 28,
  },

  {
    id: 64,
    world: 7,
    title: 'Treffe D8',
    task: 'Treffe D8',
    targets: fieldTargets('D8'),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 58,
    rewardCoins: 29,
  },

  {
    id: 65,
    world: 7,
    title: 'Treffe S4, S4',
    task: 'Treffe S4, S4',
    targets: fieldTargets('S4', 'S4'),
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 58,
    rewardCoins: 29,
  },

  {
    id: 66,
    world: 7,
    title: 'Treffe D4',
    task: 'Treffe D4',
    targets: fieldTargets('D4'),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 60,
    rewardCoins: 30,
  },

  {
    id: 67,
    world: 7,
    title: 'Treffe S2, S2',
    task: 'Treffe S2, S2',
    targets: fieldTargets('S2', 'S2'),
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 60,
    rewardCoins: 30,
  },

  {
    id: 68,
    world: 7,
    title: 'Treffe D2',
    task: 'Treffe D2',
    targets: fieldTargets('D2'),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 65,
    rewardCoins: 32,
  },

  {
    id: 69,
    world: 7,
    title: 'Treffe S1, S1',
    task: 'Treffe S1, S1',
    targets: fieldTargets('S1', 'S1'),
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 65,
    rewardCoins: 32,
  },

  {
    id: 70,
    world: 7,
    title: 'Boss – Treffe S16 → S16 → D16',
    task: 'Treffe S16 → S16 → D16',
    targets: fieldTargets('S16', 'S16', 'D16'),
    orderedTargets: true,
    sequence: ['S16', 'S16', 'D16'],
    targetHits: 3,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: true,
    rewardXP: 150,
    rewardCoins: 90,
  },

  {
    id: 71,
    world: 8,
    title: 'Treffe S20, S20',
    task: 'Treffe S20, S20',
    targets: fieldTargets('S20', 'S20'),
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 60,
    rewardCoins: 30,
  },

  {
    id: 72,
    world: 8,
    title: 'Treffe D20',
    task: 'Treffe D20',
    targets: fieldTargets('D20'),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 60,
    rewardCoins: 30,
  },

  {
    id: 73,
    world: 8,
    title: 'Treffe S10, S10',
    task: 'Treffe S10, S10',
    targets: fieldTargets('S10', 'S10'),
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 60,
    rewardCoins: 30,
  },

  {
    id: 74,
    world: 8,
    title: 'Treffe D10',
    task: 'Treffe D10',
    targets: fieldTargets('D10'),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 65,
    rewardCoins: 32,
  },

  {
    id: 75,
    world: 8,
    title: 'Treffe S5, S5',
    task: 'Treffe S5, S5',
    targets: fieldTargets('S5', 'S5'),
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 65,
    rewardCoins: 32,
  },

  {
    id: 76,
    world: 8,
    title: 'Treffe D5',
    task: 'Treffe D5',
    targets: fieldTargets('D5'),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 68,
    rewardCoins: 34,
  },

  {
    id: 77,
    world: 8,
    title: 'Treffe S1, S1',
    task: 'Treffe S1, S1',
    targets: fieldTargets('S1', 'S1'),
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 70,
    rewardCoins: 35,
  },

  {
    id: 78,
    world: 8,
    title: 'Treffe D1',
    task: 'Treffe D1',
    targets: fieldTargets('D1'),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 70,
    rewardCoins: 35,
  },

  {
    id: 79,
    world: 8,
    title: 'Erziele mindestens 80 Punkte',
    task: 'Erziele mindestens 80 Punkte',
    scoreTarget: 80,
    scoreDarts: 3,
    targetHits: null,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 72,
    rewardCoins: 36,
  },

  {
    id: 80,
    world: 8,
    title: 'Boss – Checke 52',
    task: 'Checke 52',
    checkoutTarget: 52,
    doubleOut: true,
    checkoutTip: 'S20 / D16 oder S12 / D20',
    targetHits: null,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: true,
    rewardXP: 170,
    rewardCoins: 100,
  },

  {
    id: 81,
    world: 9,
    title: 'Treffe S12, S12',
    task: 'Treffe S12, S12',
    targets: fieldTargets('S12', 'S12'),
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 70,
    rewardCoins: 35,
  },

  {
    id: 82,
    world: 9,
    title: 'Treffe D12',
    task: 'Treffe D12',
    targets: fieldTargets('D12'),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 70,
    rewardCoins: 35,
  },

  {
    id: 83,
    world: 9,
    title: 'Checke 60',
    task: 'Checke 60',
    checkoutTarget: 60,
    doubleOut: true,
    checkoutTip: 'S20 / D20',
    targetHits: null,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 70,
    rewardCoins: 35,
  },

  {
    id: 84,
    world: 9,
    title: 'Treffe S6, S6',
    task: 'Treffe S6, S6',
    targets: fieldTargets('S6', 'S6'),
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 75,
    rewardCoins: 38,
  },

  {
    id: 85,
    world: 9,
    title: 'Treffe D6',
    task: 'Treffe D6',
    targets: fieldTargets('D6'),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 75,
    rewardCoins: 38,
  },

  {
    id: 86,
    world: 9,
    title: 'Checke 50',
    task: 'Checke 50',
    checkoutTarget: 50,
    doubleOut: true,
    checkoutTip: 'S18 / D16',
    targetHits: null,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 75,
    rewardCoins: 38,
  },

  {
    id: 87,
    world: 9,
    title: 'Treffe S3, S3',
    task: 'Treffe S3, S3',
    targets: fieldTargets('S3', 'S3'),
    targetHits: 2,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 78,
    rewardCoins: 39,
  },

  {
    id: 88,
    world: 9,
    title: 'Treffe D3',
    task: 'Treffe D3',
    targets: fieldTargets('D3'),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 78,
    rewardCoins: 39,
  },

  {
    id: 89,
    world: 9,
    title: 'Checke 48',
    task: 'Checke 48',
    checkoutTarget: 48,
    doubleOut: true,
    checkoutTip: 'S16 / D16',
    targetHits: null,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 80,
    rewardCoins: 40,
  },

  {
    id: 90,
    world: 9,
    title: 'Boss – Checke 100',
    task: 'Checke 100',
    checkoutTarget: 100,
    doubleOut: true,
    checkoutTip: 'T20 / D20',
    targetHits: null,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: true,
    rewardXP: 190,
    rewardCoins: 110,
  },

  {
    id: 91,
    world: 10,
    title: 'Treffe Bull',
    task: 'Treffe Bull',
    targets: fieldTargets('Bull'),
    targetHits: 1,
    starVisitThresholds: { four: 1, three: 2, two: 3 },
    perfectDarts: 3,
    boss: false,
    rewardXP: 80,
    rewardCoins: 40,
  },

  {
    id: 92,
    world: 10,
    title: 'Treffe S20 → S19 → S18',
    task: 'Treffe S20 → S19 → S18',
    targets: fieldTargets('S20', 'S19', 'S18'),
    orderedTargets: true,
    sequence: ['S20', 'S19', 'S18'],
    targetHits: 3,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 80,
    rewardCoins: 40,
  },

  {
    id: 93,
    world: 10,
    title: 'Treffe S17 → S16 → S15',
    task: 'Treffe S17 → S16 → S15',
    targets: fieldTargets('S17', 'S16', 'S15'),
    orderedTargets: true,
    sequence: ['S17', 'S16', 'S15'],
    targetHits: 3,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 82,
    rewardCoins: 41,
  },

  {
    id: 94,
    world: 10,
    title: 'Treffe S14 → S13 → S12',
    task: 'Treffe S14 → S13 → S12',
    targets: fieldTargets('S14', 'S13', 'S12'),
    orderedTargets: true,
    sequence: ['S14', 'S13', 'S12'],
    targetHits: 3,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 82,
    rewardCoins: 41,
  },

  {
    id: 95,
    world: 10,
    title: 'Treffe S11 → S10 → S9',
    task: 'Treffe S11 → S10 → S9',
    targets: fieldTargets('S11', 'S10', 'S9'),
    orderedTargets: true,
    sequence: ['S11', 'S10', 'S9'],
    targetHits: 3,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 85,
    rewardCoins: 42,
  },

  {
    id: 96,
    world: 10,
    title: 'Treffe S8 → S7 → S6',
    task: 'Treffe S8 → S7 → S6',
    targets: fieldTargets('S8', 'S7', 'S6'),
    orderedTargets: true,
    sequence: ['S8', 'S7', 'S6'],
    targetHits: 3,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 85,
    rewardCoins: 42,
  },

  {
    id: 97,
    world: 10,
    title: 'Treffe S5 → S4 → S3',
    task: 'Treffe S5 → S4 → S3',
    targets: fieldTargets('S5', 'S4', 'S3'),
    orderedTargets: true,
    sequence: ['S5', 'S4', 'S3'],
    targetHits: 3,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 90,
    rewardCoins: 45,
  },

  {
    id: 98,
    world: 10,
    title: 'Treffe S2 → S1 → Bull',
    task: 'Treffe S2 → S1 → Bull',
    targets: fieldTargets('S2', 'S1', 'Bull'),
    orderedTargets: true,
    sequence: ['S2', 'S1', 'BULL'],
    targetHits: 3,
    starVisitThresholds: { four: 2, three: 3, two: 4 },
    perfectDarts: 6,
    boss: false,
    rewardXP: 90,
    rewardCoins: 45,
  },

  {
    id: 99,
    world: 10,
    title: 'Treffe S20 → D20 → T20',
    task: 'Treffe S20 → D20 → T20',
    targets: fieldTargets('S20', 'D20', 'T20'),
    orderedTargets: true,
    sequence: ['S20', 'D20', 'T20'],
    targetHits: 3,
    starVisitThresholds: { four: 3, three: 4, two: 5 },
    perfectDarts: 9,
    boss: false,
    rewardXP: 100,
    rewardCoins: 50,
  },

  {
    id: 100,
    world: 10,
    title: 'Boss – Treffe S20 → S10 → S5 → S1 → S2',
    task: 'Treffe S20 → S10 → S5 → S1 → S2',
    targets: fieldTargets('S20', 'S10', 'S5', 'S1', 'S2'),
    orderedTargets: true,
    sequence: ['S20', 'S10', 'S5', 'S1', 'S2'],
    targetHits: 5,
    starVisitThresholds: { four: 3, three: 4, two: 5 },
    perfectDarts: 9,
    boss: true,
    rewardXP: 250,
    rewardCoins: 150,
  },
]


